Grams bug
svsticky/fluffy-bassoon pull request #2
Opened 2019-10-18 14:38 UTC by armaatus

fixed that grams get stored in the amount colomn

2019-10-30 15:32 UTC, Mstiekema requested changes

2019-10-30 15:32 UTC, Mstiekema commented on files/Main.js
> +  //calculateDiscounts(inputFieldBo);
Remove comment

2019-11-01 13:10 UTC, Mstiekema submitted a review, later dismissed

2019-11-18 15:56 UTC, Riscky commented on files/Main.js
> +function compareProducts( a, b ) {
this is unused

2019-11-18 16:24 UTC, Riscky approved these changes
looks good, please split changes in multiple PR next time

2019-11-18 16:25 UTC, merged